defaults: &defaults
  working_directory: ~/tmp/personal-site
  docker:
    - image: circleci/node:10.10.0

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/personal-site
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/personal-site
      - run:
          name: Run tests
          command: npm test
  deploy-master:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/personal-site
      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          command: |
            now --token $ZEIT_TOKEN \
            --local-config ./.now/now.production.json \
            --env SITE_COMMIT_SHA1=$CIRCLE_SHA1 \
            --env SITE_BUILD_URL=$CIRCLE_BUILD_URL
            now --token $ZEIT_TOKEN \
            --local-config ./.now/now.production.json alias

workflows:
  version: 2
  deploy:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - deploy-master:
          requires:
            - test
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
